### PR TITLE
Cli default param fix

### PR DESCRIPTION
**Pull request by carrollgt91**
Updates `ipfsUrl` to use a multiaddr (see https://github.com/multiformats/multiaddr)  instead of  a URI.

### CODE REVIEW

**Review by kevinahuber — APPROVED** [review]
👍

**Comment by anoff** [comment]
Does the ipfs-api throw if you don't provide the correct format or would it be worth a small `assert()` to make sure a valid string is passed?

**Comment by carrollgt91** [comment]
It doesn't seem to - I'm able to get past the instantiation of the API without it failing. I'll get something in for that real quick.

**Comment by carrollgt91** [comment]
... this turned out to be a bit more work to validate properly. We can create an issue for it if we want, but I'm signing off for the now 👍

**Pull request merged**
